/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.UnityRosBridge
{
    public class Xuan : Message
    {
        public const string RosMessageName = "unity_ros_bridge/Xuan";

        public Header header { get; set; }
        public float servo_angle { get; set; }
        public float speed { get; set; }
        public float mode2_pitch { get; set; }

        public Xuan()
        {
            this.header = new Header();
            this.servo_angle = 0.0f;
            this.speed = 0.0f;
            this.mode2_pitch = 0.0f;
        }

        public Xuan(Header header, float servo_angle, float speed, float mode2_pitch)
        {
            this.header = header;
            this.servo_angle = servo_angle;
            this.speed = speed;
            this.mode2_pitch = mode2_pitch;
        }
    }
}
